# Generated by Django 5.1.4 on 2025-01-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("group", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[("Head", "Head"), ("Member", "Member")], max_length=10
                    ),
                ),
            ],
        ),
    ]
