# Generated by Django 5.1.4 on 2025-01-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_alter_member_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={},
        ),
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name="member",
            table="members",
        ),
    ]
