name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Decode and create firebase_key.json
      - name: Decode firebase_key.json
        run: |
          echo "${{ secrets.FIREBASE_KEY_BASE64 }}" | base64 -d > ./backend/firebase_key.json

      # Step 4: Install dependencies
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Step 5: Run tests (optional)
      - name: Run tests
        working-directory: ./backend
        run: |
          source venv/bin/activate
          python manage.py test

      # Step 6: Build Docker image
      - name: Build Docker image
        working-directory: ./backend
        run: docker build -t django-backend .

      # Step 7: Push Docker image to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        working-directory: ./backend
        run: |
          docker tag django-backend ${{ secrets.DOCKER_USERNAME }}/django-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/django-backend:latest

      # Step 8: Deploy to AWS EC2 using SSM and clean up Python files
      - name: Deploy using AWS SSM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=${{ secrets.INSTANCE_ID }}" \
            --parameters 'commands=[
              "docker pull ${{ secrets.DOCKER_USERNAME }}/django-backend:latest",
              "docker stop django-backend || true",
              "docker rm django-backend || true",
              "find . -name \"*.pyc\" -exec rm -f {} \\;",
              "find . -name \"__pycache__\" -exec rm -rf {} +",
              "python -m compileall .",
              "docker run -d --name django-backend -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/django-backend:latest"
            ]' \
            --region ${{ secrets.AWS_REGION }}