name: Django CI/CD

on:
  push:
    branches:
      - CI/CD-Pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Step 4: Run tests (optional)
      - name: Run tests
        working-directory: ./backend
        run: |
          source venv/bin/activate
          python manage.py test

      # Step 5: Build Docker image
      - name: Build Docker image
        working-directory: ./backend
        run: docker build -t django-backend .

      # Step 6: Push Docker image to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        working-directory: ./backend
        run: |
          docker tag django-backend ${{ secrets.DOCKER_USERNAME }}/django-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/django-backend:latest

      # Step 7: Deploy to AWS EC2 using SSM
      - name: Deploy using AWS SSM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=${{ secrets.INSTANCE_ID }}" \
            --parameters 'commands=["docker pull ${{ secrets.DOCKER_USERNAME }}/django-backend:latest","docker stop django-backend || true","docker rm django-backend || true","docker run -d --name django-backend -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/django-backend:latest"]' \
            --region ${{ secrets.AWS_REGION }}